import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/navcomponents/Navbar'
import ToasterProvider from './providers/ToasterProvider'



export const metadata: Metadata = {
  title: 'Auction of Azerbaijan',
  description: 'Generated by create next app',
  icons:
  {
    icon:['/favicon.ico?v=4']
  }    
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ToasterProvider/>
      <Navbar/>
      <main className='container mx-auto px-5 pt-10'>
          {children}
      </main>
        </body>
    </html>
  )
}
