services:
     postgres:
         image: postgres
         environment:
             - POSTGRES_PASSWORD=serger.11
         ports:
             - 5432:5432
         volumes:
             - pgdata:/var/lib/postgressql/data
volumes:
  pgdata:
